---
functional:
  - Пользователь может зарегистрироваться на сайте либо авторизоваться,
    используя аккаунт в Github или  Discord.
  - Пользователь может с помощью емейла сменить пароль, если забыл его.
  - Пользователь может отслеживать свои рейтинг и ранг, а также просматривать
    статистику своих игр в профиле.
  - Пользователи получают очки, на основе которых строится рейтинг за неделю,
    месяц и за все время.
  - Пользователь может просматривать профили других пользователей.
  - Пользователь может начать игру с ботом без регистрации.
  - Пользователь может создать игру с ботом, любым человеком или другом (ему
    придет приглашение).
  - Пользователь может присоединиться к уже созданной игре.
  - Пользователь может выбрать игру по уровню сложности.
  - При создании игры можно выбрать определенную игру, иначе она будет подобрана
    наугад.
  - Каждый игрок может видеть код  соперника в режиме онлайн.
  - Каждый игрок может выбрать язык, на котором будет выполнять задачу игры.
  - Задачи даны на двух языках — русском и английском.
  - Другие пользователи могут следить за ходом игры.
  - В игре есть чат, в котором могут общаться зарегистрированные пользователи.
  - Игра может длиться неограниченное время.
  - Если вдруг один из игроков вылетел из игры, второй может продолжать играть.
    Первый в любой момент игры, пока она не закончена, может переподключиться в
    игру.
  - Победивший игрок может покинуть игру, а проигравший – остаться и закончить
    задание.
  - Завершенная игра доступна в записи.
  - Редактор для ввода кода выглядит как проигрыватель.
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован
    для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен быть удобным на мобильном устройстве.
  - Сайт должен быть протестирован на совместимость с последними версиями
    браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика (например,
    1000 одновременных пользователей).
implicit: null
