---
functional:
  - Пользователь может зарегистрироваться на сайте либо авторизоваться,
    используя аккаунт в Github или  Discord.
  - Пользователь может с помощью емейла сменить пароль, если забыл его.
  - Пользователь может отслеживать свои рейтинг и ранг, а также просматривать
    статистику своих игр в профиле.
  - Пользователи получают очки, на основе которых строится рейтинг за неделю,
    месяц и за все время.
  - Пользователь может просматривать профили других пользователей.
  - Пользователь может начать игру с ботом без регистрации.
  - Пользователь может создать игру с ботом, любым человеком или другом (ему
    придет приглашение).
  - Пользователь может присоединиться к уже созданной игре.
  - Пользователь может выбрать игру по уровню сложности.
  - При создании игры можно выбрать определенную игру, иначе она будет подобрана
    наугад.
  - Каждый игрок может видеть код  соперника в режиме онлайн.
  - Задачи даны на двух языках — русском и английском.
  - Другие пользователи могут следить за ходом игры.
  - В игре есть чат, в котором могут общаться зарегистрированные пользователи.
  - Игра может длиться неограниченное время.
  - Если вдруг один из игроков вылетел из игры, второй может продолжать играть.
    Первый в любой момент игры, пока она не закончена, может переподключиться в
    игру.
  - Завершенная игра доступна в записи.
  - Редактор для ввода кода выглядит как проигрыватель.
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован
    для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен быть удобным на мобильном устройстве.
  - Сайт должен быть протестирован на совместимость с последними версиями
    браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика (например,
    1000 одновременных пользователей).
implicit:
  - Интуитивно понятный интерфейс  без лишних сложностей.
  - (Доработка) Система матчмейкинга (возможность создавать игру со случайными
    игроками, учитывая их рейтинг и ранг).
  - Механизм контроля за честностью игрового процесса (модерация и выявления
    использования читов).
  - Возможность оставлять обратную связь и реагирование на неё для улучшения
    опыта игроков.
  - Функционал для взаимодействия между игроками (чат, форум, возможность
    добавления в друзья).
  - (Доработка) Возможность редактировать свой профиль (изменять емейл,
    указанный при регистрации, аватар, никнейм) и удалять его.
  - (Доработка) Монетизация. Возможность для пользователей приобретения премиум
    доступа с расширенным функционалом, предоставляющим дополнительные
    возможности, инструменты или контент в игре.
  - (Доработка) Подтверждение адреса электронной почты через ссылку в письме
    после регистрации поможет предотвратить ситуации, когда пользователь
    указывает неверный адрес, что может привести к невозможности смены пароля в
    будущем из-за неверной или недоступной электронной почты.
